<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <NuGetAudit>false</NuGetAudit>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>ddf36fd8-9f6d-4f6a-b0f4-92d6e05db54e</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="11.9.2" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="nuget.config" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Logging\" />
    </ItemGroup>

</Project>
